name: some
on: [ push ]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola"
  manual:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: 
      - run: echo "Hola"
